### ISSUE TITLE
Proxy issue with the Python sdk

### ISSUE THREAD

**Issue by timberbee** [EvidentSecurity/esp-sdk-python#12]

**Comment by timberbee** [comment]
The following is a summary of an issue reported by Barclays back in May of 2017.
` looking at the unzipped SDK, it seems to use the python “urllib3” module (as opposed to “requests”), that’s a bit trickier through proxies from my experience. In fact, just looking through the rest.py, it seems to use urllib3.PoolManager, which is not proxy aware (urllib3.ProxyManager is)` 
Can we update the python sdk to include Requests for them?

**Comment by zimmermanc** [comment]
https://github.com/EvidentSecurity/esp-sdk-python/pull/17

Added a pull request but I realize this needs to be ported to the swagger template codegen.

**Comment by zimmermanc** [comment]
https://github.com/EvidentSecurity/esp-sdk-python/pull/18/
please close
