### ISSUE TITLE
esp.Signature(name_cont='dns') results in TypeError

### ISSUE THREAD

**Issue by cityshrimp** [EvidentSecurity/esp-sdk-python#17]
Running `signatures = esp.Signature.where(name_cont='dns')` results in the following error:

```
  File "/usr/local/lib/python2.7/site-packages/esp/resource.py", line 131, in find_class_for_resource
    dynamically_created_object = type(underscore_to_titlecase(name), (ESPResource,), {})
TypeError: type() argument 1 must be string, not unicode
```

This doesn't happen if I run something like `teams = esp.Team.where(name_cont='s')`.

Seems like something doesn't work correctly `Signature` search specifically.

**Comment by hutch34** [comment]
Fixed in https://github.com/EvidentSecurity/esp-sdk-python/commit/18b73080018335b12a917d2b44ca3bc6fcd12ee2
