### ISSUE TITLE
cacert.pem is missing

### ISSUE THREAD

**Issue by cilynx** [EvidentSecurity/esp-sdk-python#2]
Whether you install from `pip` or `./setup.py install`, `cacert.pem` is missing from `site-packages/esp/packages/requests/`.  This shows up as an SSL error when attempting to connect:
 
`esp.packages.requests.exceptions.SSLError: [Errno 2] No such file or directory`

From digging around a bit, it appears that `requests` has broken out its certificates to a new package called `certifi` for the `pip` scenario.  Installing manually can get a bit more involved as discussed in [multiple](https://github.com/maxtepkeev/python-redmine/issues/109) [threads](http://stackoverflow.com/questions/15157502/requests-library-missing-file-after-cx-freeze).

To work around, you can simply copy `esp-sdk-python/esp/packages/requests/cacert.pem` to `site-packages/esp/packages/requests/`, but I imagine there's a more robust solution that can be effected via `setup.py`.

**Comment by kyleterry** [comment]
So I'm vendoring the requests library to make the ESP SDK vendorable itself. I think the root cause of this is that setup.py is not tagging the certs file as a data source it should include in the package when it's uploaded.

I'll take a look at this tomorrow. Should be an easy fix.

**Comment by kyleterry** [comment]
Fixed with 21c3564242f81c7fea6795ba678fd0012eff5a73
