### ISSUE TITLE
py SDK UsersAPI bug

### ISSUE THREAD

**Issue by toddm92** [EvidentSecurity/esp-sdk-python#3]
py SDK UsersAPI bug:

The 'team_ids' attribute does not work properly.  The example below creates a user successfully, but adds the new user to **all** ESP teams.

```
users_api = esp_sdk.UsersApi()
esp_user = users_api.create("Jim", "Beam", "jimbo@rock.io", role_id="3", team_ids=[97])
```

When calling the '/api/v2/users' endpoint directly with the attributes below, the new user is added to the appropriate ESP team as expected.

```
data = '{"data": {"type": "users", "attributes": {"first_name": "Jim", "last_name": "Beam", "email": "jimbo@rock.io", "role_id": "3", "team_ids": [97]}}}'
```

**Comment by johnathanludwig** [comment]
This was fixed on the API side and should return an error now.
